### ISSUE TITLE
Unable to install, no package called 'Aqd' on crates.io

### ISSUE THREAD

**Issue by rickbeeloo** [hyperledger/solang-aqd#18]
The Github says:
`cargo install --force --locked aqd` to install this.
However this fails with:
```
error: could not find `aqd` in registry `crates-io` with version `*`
```
Which makes sense as there is no pacakge called "Aqd" on [crates.io](https://crates.io/search?q=aqd).

How should this be installed?

**Comment by tareknaser** [comment]
Apologies for the confusion. 

Currently, `Aqd` is not published on crates.io. You can still use it by building it from the source. Here are the steps:
1. Clone the repository: `git clone https://github.com/hyperledger/solang-aqd.git`
2. Navigate to the core crate directory: `cd solang-aqd/crates/aqd-core`
3. Install the tool: `cargo install --force --locked --path .`

We plan to publish `Aqd` on crates.io soon. In the meantime, these steps should allow you to use it. 
Let us know if you encounter any issues or have further questions!

**Comment by AlvinKuruvilla** [comment]
When using these build instructions, the compiler fails to build the project because ahash doesn't have a stdsimd feature. When diving into this. I had to upgrade subxt = "0.34.0" and all the anyhow dependencies to anyhow = "1.0.80". 

However, even after that, I still got the same error. I realized that, for some reason, deep in the dependency chain, the compiler was pulling hyper = 0.14.7, which also brought in the problematic ahash dependency. I removed `-locked` from your instructions to try and fix that. But now the compiler complains that
error[E0599]: no method named `opt_type` found for reference `&ReturnTypeSpec<PortableForm>` in the current scope
in the cargo-contract git dependency. 

Apologies for the long-winded reply 😅

**Comment by tareknaser** [comment]
@AlvinKuruvilla 

Thanks for reporting the issue 

You shouldn't need to manually upgrade any dependencies. 
Could you give me the full error you get when you run `cargo install --force --locked --path .` without bumping any dependencies or removing `Cargo.lock`?

Also make sure you have `libudev` installed.

**Comment by AlvinKuruvilla** [comment]
Strangely enough, I had just wiped my Mac (for other reasons) and did a fresh clone and install with your instructions and it seems to have worked now 😅.  If you would like any support to try and bring this package to crates.io, I would be more than happy to try and contribute to the effort in whatever little ways I can :). 

I don't remember what rust version I was running with when I tried it before (pretty sure I was on stable), but now I was using   `stable-aarch64-apple-darwin unchanged - rustc 1.76.0 (07dca489a 2024-02-04)`

**Comment by tareknaser** [comment]
I also run on mac but I tested on linux yesterday just to double check


>  If you would like any support to try and bring this package to crates.io, I would be more than happy to try and contribute to the effort 

Thanks! We are still working on some issues to get `solang-aqd` to work for Solang compiled Polkadot smart contracts. once we got them solved, we will publish `aqd` to crates.io

**Comment by alexeys-magicsquare** [comment]
how could be resolved? error: older versions of the `wasm-bindgen` crate are incompatible with current versions of Rust; please update to `wasm-bindgen` v0.2.88
